### ISSUE TITLE
array_keys_exist function does not Exist.

### ISSUE THREAD

**Issue by TwDover** [LoneFry/LastWord#1]
/**
 * Determine if the specified array contains all the specified keys
 *
 * @param array $keys   Keys to seek
 * @param array $search Array to seek in
 *
 * @return bool
 */
function array_keys_exist($keys, $search) {
    // If we were passed a single key, use existing function
    if (!is_array($keys)) {
        return array_key_exists($keys, $search);
    }
    // If there are no keys in $search that are not in $keys
    // We have all the keys
    return [] == array_diff($keys, array_keys($search));
}

Should be added to ^/lib/functions

**Comment by LoneFry** [comment]
You'll find that function in the current version of Graphite: https://github.com/LoneFry/Graphite/blob/master/src/%5E/lib/functions.php#L152
